[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86"

[default_config.opts]
compiler = "nasm"
compile_flags_txt = [
    "-fwin32",
    "main.s",
]
diagnostics = true
default_diagnostics = false
